<?php

namespace YouCast\Gemini\Gemini\Enums;

enum HarmCategory: string
{
    case HATE_SPEECH = 'HARM_CATEGORY_HATE_SPEECH';
    case SEXUALLY_EXPLICIT = 'HARM_CATEGORY_SEXUALLY_EXPLICIT';
    case HARASSMENT = 'HARM_CATEGORY_HARASSMENT';
    case DANGEROUS_CONTENT = 'HARM_CATEGORY_DANGEROUS_CONTENT';
    case CIVIC_INTEGRITY = 'HARM_CATEGORY_CIVIC_INTEGRITY';
}
